"""
Task 1 
Question 13

Command Used:
    python manage.py makemigrations

Purpose:
- The makemigrations command compares the models defined in models.py
  with the current database schema.
- It generates migration files containing the instructions required
  to create or modify database tables.
- It does not make any changes to the database.

Generated Migration File:
    courses/migrations/0001_initial.py

CreateTable (CreateModel) Operations Found:
- CreateModel for Department
- CreateModel for Course
- CreateModel for Student
- CreateModel for Enrollment


Question 14

Commands Used:
    python manage.py migrate

Purpose:
- Applies all pending migrations to the database.
- Reads the migration files generated by makemigrations.
- Converts CreateModel operations into SQL CREATE TABLE statements.
- Creates the corresponding database tables.

Verification:
The database was verified using the SQLite Viewer extension in VS Code.

Application tables created:
- courses_department
- courses_course
- courses_student
- courses_enrollment

Additional Django tables:
- auth_user
- auth_group
- auth_permission
- django_admin_log
- django_content_type
- django_migrations
- django_session

Observation:
The application tables currently contain zero rows because only the table
structure has been created. No data has been inserted yet.



Task 2
Question 17

Command Used:
    Course.objects.filter(department__name="Computer Science")

Purpose:
- Retrieves all Course objects that belong to the Computer Science department.

Explanation:
- filter() returns all objects that satisfy the given condition.
- The double underscore (__) is used to traverse relationships between models.
- department__name means:
      Start from the Course model,
      follow the ForeignKey to the Department model,
      and compare the Department's name field.
- Django ORM automatically performs the required SQL JOIN behind the scenes.

Equivalent SQL:
SELECT *
FROM courses_course
JOIN courses_department
ON courses_course.department_id = courses_department.id
WHERE courses_department.name = 'Computer Science';

"""